Feature/#19add error function
shinonome-inc/mobile_shu_mogi_Qclient pull request #20
Opened 2021-01-18 13:26 UTC by ShuheiYoshidaJP

- Issue
    - #19
- 詳細
    - FeedVCにおいて
        - リクエスト回数制限を超えた場合
            - エラー発生例
                - ページスクロールを何度も行う
            - エラーハンドリング
                - エラー画面に遷移させる
                    - ログイン画面に戻るか再度リクエストを送るかを選択できる
    - ArtickePageVCにて
        - 通信状態が悪い場合
            - エラー発生例
                - モバイルデータ通信・WiFi通信を切ってロードさせる
            - エラーハンドリング
                - エラー画面に遷移
                    - ログイン画面に戻るか再度ページ読み込みを選択できる
    - MyPageVCにて
        - トークン認証ができなかった場合
            - エラー発生例
                - 無効なトークンが入力されている
                - トークンが入力されていない状態でMyPageVCを開こうとした
            - エラーハンドリング
                - エラー画面に遷移
                    - ログイン画面に戻れる
- 困っていること
    - Alamofireで通信を行うとき、かつ、通信状態が悪いときエラー検出ができていない
    - 検証したこと
        - 以下のalamofireの通信エラーでエラーを発見できないか検証したが発見できなかった
            -  error.responseCode == NSURLErrorNotConnectedToInternet
        - 参考サイト
            - [Swift2 - Alamofire のリクエストでネットワークエラーを検知する](https://takanamishi.hatenablog.jp/entry/2016/06/06/235940)

2021-01-20 01:59 UTC, mcz9mm requested changes
コメントしました

2021-01-20 01:59 UTC, mcz9mm commented on Qcli/Extensions/LoginViewController+UITextFieldDelegate.swift
> +    internal func setUpNotificationForTextField() {
今回キーボードで隠れないようにやってもらっていい感じにできてるね。
直す必要は無いけど、実はとっても便利なライブラリがあるから今度試してみて。
AppDelegateに設定書くだけで全画面対応してくれるやつ。

ただ、仕組みを知るという意味では今回の実装で学んでもらったと思うのでバッチリです。

https://github.com/hackiftekhar/IQKeyboardManager

2021-01-20 01:59 UTC, mcz9mm commented on Qcli/Type+Option/QiitaError.swift
> +enum QiitaError: Error {
👍

2021-01-20 01:59 UTC, mcz9mm commented on Qcli/Identifier/ViewControllerIdentifier.swift
> +enum ViewControllerIdentifier: String {
👍

2021-01-20 01:59 UTC, mcz9mm commented on Qcli/ViewController/ErrorViewController.swift
> +class ErrorViewController: UIViewController {
個人的にはこいつはUIViewで事足りそうだなぁ
Figmaのデザイン見てもらえればわかるけど、遷移させずに現在表示している画面上に出せると良いね。

2パターンあると思ってて
・各画面にErrorViewを配置しておいて(初期でHiddenにしておけば見えない)、エラー時に表示
→各画面に配置する必要あり、それぞれ配置するので面倒だが画面別にデザインなどカスタム可能
・現在表示中のViewControllerを取得してその画面の上に`addSubView`するやり方
→今回作ってもらった画面をUIViewに変更、高さやポジションを調整して表示する

shu君がやってもらったのだと後者の方がイケてるし管理が楽になりそうね。

```
    func getTopViewController() -> UIViewController? {
        if let rootViewController = UIApplication.shared.windows.filter({$0.isKeyWindow}).first?.rootViewController {
            var topViewController: UIViewController = rootViewController

            while let presentedViewController = topViewController.presentedViewController {
                topViewController = presentedViewController
            }

            return topViewController
        } else {
            return nil
        }
    }

/// 使う時
    if let topViewController = getTopViewController() {
        // 任意のUIView
        var hoge = UIView()
        hoge.backgroundColor = .red
        hoge.frame = CGRect(x: 0.0, y: 0.0, width: 300, height: 300)
        topViewController.view.addSubview(hoge)
    }
```


<img width="300" alt="スクリーンショット 2021-01-20 10 39 21" src="https://user-images.githubusercontent.com/11751495/105116003-32357a00-5b0d-11eb-8cdb-a918e6887a9e.png">

<img width="300" alt="スクリーンショット 2021-01-20 10 39 31" src="https://user-images.githubusercontent.com/11751495/105115992-2ea1f300-5b0d-11eb-990d-7ff75c3ab1e0.png">

2021-01-20 02:12 UTC, mcz9mm commented on Qcli/ViewController/ErrorViewController.swift
> +class ErrorViewController: UIViewController {
試しに`ArticlePageViewController`でやったらこんな感じにできたのでいけると思う。

```
extension ArticlePageViewController: ErrorDelegate {
    func segueErrorViewController(qiitaError: QiitaError) {

        if let topViewController = getTopViewController() {

            var hoge = UIView()
            hoge.backgroundColor = .red
            // 84.0 = NavigationSize(64.0) + StatusbarSize(20.0)
            hoge.frame = CGRect(x: 0.0, y: 84.0, width: topViewController.view.frame.width, height: topViewController.view.frame.height)
            topViewController.view.addSubview(hoge)
        }
    }
```

<img width="300" alt="スクリーンショット 2021-01-20 11 07 19" src="https://user-images.githubusercontent.com/11751495/105117714-50e94000-5b10-11eb-9648-7d8a0edc6d45.png">

2021-01-23 06:01 UTC, ShuheiYoshidaJP commented on Qcli/ViewController/ErrorViewController.swift
> +class ErrorViewController: UIViewController {
kaoruさんに考えていただいたgetTopViewController()メソッドというのはいろんなVCで使われるかと思われるのですが、
kaoruさんだったら各VCで使われうような関数はどのような場所に定義されますか？

2021-01-23 06:54 UTC, ShuheiYoshidaJP commented on Qcli/ViewController/ErrorViewController.swift
> +class ErrorViewController: UIViewController {
[この問題](https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/20#discussion_r563024648)に関して解決しました。
ErrorViewクラスを新たに作成し、そのクラス内にメソッドとして配置しようと思います。

2021-01-23 13:09 UTC, ShuheiYoshidaJP commented
- 現在
    - ErrorVCのViewだけをエラーが起きた時各VCに表示できるようにした
- 実装内容
    - ErrorVCにおいて
        - checkSafeAreaメソッドを設置
        - navigationBarHeightとtabBarHeightを取得しviewのheightから引く
        - safeAreaInsetsを使うのも検討したが、MyPageVCでのsafeAreaInsetsの取得が間に合わない
            - [【iOS】safeAreaInsetsの値が取得できるタイミング](https://qiita.com/hituziando/items/e5873b5bfa42247071e6)
    -  segueErrorViewControllerにおいて
        - ErrorVCのcheckSafeAreaメソッドを実行
        -  addChild
        -  view.addSubviewでエラー画面表示
- なぜErrorViewを使わないのかについて
    - コードでのレイアウト設定が大変
    - 一応ErrorViewも残してある
        - 実行しようとするとエラーが出る

2021-01-23 13:51 UTC, ShuheiYoshidaJP commented
@mcz9mm 
エラー画面の修正をしました。
お時間があるときに再度レビューお願いいたします。

2021-01-25 04:52 UTC, mcz9mm requested changes
コメントしました！
FigmaからErrorViewで使う画像のエクスポートしてください！

2021-01-25 04:52 UTC, mcz9mm commented on Qcli/FetchData/AirticleDataNetworkService.swift
>                      print("Failed to get error message.")
こことか[52](https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/20/files#diff-a039353ea20454fe2318fa25c1d6ae0bbd3dacc8d27106a2c81cc6dcb5cb3710L52)行目にはエラーは出さない？

2021-01-25 04:52 UTC, mcz9mm commented on Qcli/FetchData/AuthDataNetworkService.swift
>                      print("Failed to get error message.")
ここと[53](https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/20/files#diff-1e7caff166a20acdb5c6a2cbf19cf9144eb6d4b6ee99331db4a6affa086a68c9L53)行目も同じくエラーを出してあげるべき場所かな

2021-01-25 04:52 UTC, mcz9mm commented on Qcli/FetchData/TagDataNetworkService.swift
>                      print("Failed to get error message.")
同様！
https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/20/files#diff-345ef55bb94cce37121304b43848e131a10d2983ae3f81cb8eedbb276ef20f74R58

2021-01-25 04:52 UTC, mcz9mm commented on Qcli/View/ErrorView.swift
> +    var reloadButton: UIButton!
おぉ、コードで全部やったのね！

xibとかにカスタムViewとしてあげるとエラーのデザインチェックも簡単なのと修正が用意になるので、
できればxib化してあげて欲しい！！

調べた感じだとこの辺りが参考になりそうかと。
xibの読み込みはtableviewCellとほぼ同様なのでこの機会にできる様になりましょ
https://qiita.com/maebaru/items/90f915f82e3d6425cbdc

2021-01-25 12:14 UTC, ShuheiYoshidaJP commented on Qcli/FetchData/AirticleDataNetworkService.swift
>                      print("Failed to get error message.")
修正しました。

2021-01-25 12:14 UTC, ShuheiYoshidaJP commented on Qcli/FetchData/AuthDataNetworkService.swift
>                      print("Failed to get error message.")
修正しました。

2021-01-25 12:14 UTC, ShuheiYoshidaJP commented on Qcli/FetchData/TagDataNetworkService.swift
>                      print("Failed to get error message.")
修正しました。

2021-01-25 12:16 UTC, ShuheiYoshidaJP commented
@mcz9mm 
修正いたしました。
お時間あるときに、ご確認よろしくお願いします。

2021-01-26 06:58 UTC, ShuheiYoshidaJP commented
[補足](https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/issues/19#issuecomment-767344622https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/issues/19#issuecomment-767344622https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/issues/19#issuecomment-767344622)

2021-01-26 12:52 UTC, mcz9mm commented
画像サイズとかフォント数とかも反映できないかな？
他は問題ないです。

<img width="750" alt="スクリーンショット 2021-01-26 21 50 21" src="https://user-images.githubusercontent.com/11751495/105847153-9205b680-6020-11eb-83c1-0b2091755d9f.png">

<img width="388" alt="スクリーンショット 2021-01-26 21 50 12" src="https://user-images.githubusercontent.com/11751495/105847144-8fa35c80-6020-11eb-8dbf-c6d9c661dd96.png">

2021-01-26 14:03 UTC, ShuheiYoshidaJP commented
![IMG_ED97F7293650-1](https://user-images.githubusercontent.com/62702170/105854607-70113180-602a-11eb-9e2d-be544b7dd0e0.jpeg)
フォントサイズと画像のサイズを変更しました。
ご確認よろしくお願いします。

2021-01-27 05:57 UTC, merged