Feature/#21change loading UI display
shinonome-inc/mobile_shu_mogi_Qclient pull request #22
Opened 2021-01-29 08:14 UTC by ShuheiYoshidaJP

## ISSUE
#21 

## 詳細
* 修正ファイル
    * FeedVC
    * TagListVC
    * TagDetailVC
    * MyPageVC
    * UserDetailVC
* 修正箇所
    * 各VCにて
        * dataItems監視
            * didSet
                * tableView.relaodData
        * tableView refresh control導入
            * refreshメソッド
                * dataItems中身削除
                * データ取得
    * MyPageVCにて
        * データ取得してからLabelに表示

2021-01-29 08:41 UTC, mcz9mm requested changes
UIRefreshControl()については他の画面でも同様なので確認お願いします！

2021-01-29 08:41 UTC, mcz9mm commented on Qcli/ViewController/FeedViewController.swift
> +        didSet {
didSetとwillSetもあるので機会があれば使ってみてね

2021-01-29 08:41 UTC, mcz9mm commented on Qcli/ViewController/FeedViewController.swift
> +        articleTableView.refreshControl = UIRefreshControl()
`UIRefreshControl()`はletか何かでクラス内プロパティで持っていても良いかな。
わざわざTableViewから取り出してやってるのでも良いけど、毎回使うタイミングでguardなり使って
アクセスしてるの面倒そうだし。

2021-01-29 08:41 UTC, mcz9mm commented on Qcli/ViewController/FeedViewController.swift
> +        articleTableView.refreshControl = UIRefreshControl()
もしくはオプショナルでアクセスして、ない場合は結局nilでguardと同様使えないだけなので
↓のコードの様にしてみるのもアリ。どっちでも！
```
articleTableView.refreshControl = UIRefreshControl()
articleTableView.refreshControl?.addTarget(self, action: #selector(refresh), for: .valueChanged)

--------------

articleTableView.refreshControl?.endRefreshing()
```

2021-01-29 08:41 UTC, mcz9mm commented on Qcli/ViewController/TagDetailListViewController.swift
> +        guard let nib = Bundle.main.loadNibNamed("ErrorView", owner: self, options: nil) else { return }
ここエラー画面のPRで見逃しちゃったけど、`nib`→`ErrorView`の取得はErrorViewクラスでやってあげたいな。
いちいち実装側でこれを記述するのは手間そうなのと管理コストが大きいので。

2021-01-30 04:41 UTC, ShuheiYoshidaJP commented on Qcli/ViewController/FeedViewController.swift
> +        articleTableView.refreshControl = UIRefreshControl()
refreshControlをクラス内プロパティ化しました。

2021-01-30 05:52 UTC, ShuheiYoshidaJP commented
@mcz9mm 
修正しました。
お時間ある時にご確認よろしくお願いします。

2021-02-03 10:21 UTC, mcz9mm approved these changes
遅くなってごめん！
LGTM ![](https://media.giphy.com/media/GCvktC0KFy9l6/giphy.gif)

2021-02-03 10:21 UTC, mcz9mm commented on Qcli/View/ErrorView.swift
> +    static func make() -> ErrorView {
👍

2021-02-03 10:22 UTC, merged